version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: sheerun:master    # Required. Must be in the same fork network.
    autoMerge: true
    mergeMethod: merge    # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
label: ":arrow_heading_down: pull"  # Optional